### ISSUE TITLE
New Windows binary?

### ISSUE THREAD

**Issue by gd4c** [tostercx/hidec#1]
Hi, this seems like a useful tool. Unfortunately, the binary link in the ReadMe expired.

Could you please put a build here in GitHub releases?

Thank you

**Comment by tostercx** [comment]
Uhh, too lazy to do it atm, here's some alternatives:

https://github.com/stbrenner/SilentCMD

https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/andrew-grechkin/hidcon-v1.1.4.7z

http://www.nirsoft.net/utils/nircmd.html (think it was `nircmd exec hide <your exe>` or sth)

**Comment by gd4c** [comment]
The old binary is lost? Bummer.

Anyway thanks for the links and please post yours if you ever got to it/found it!

Thanks
